---
# tasks file for sbaerlocher.qemu-guest-agent

- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: install Qemu Guest Agent
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ qemu_package }}"
  when: ansible_system_vendor == 'qemu'
  notify:
    - enabled Qemu Guest Agent
    - restart Qemu Guest Agent
  tags:
    - packages
